version: '3.8'
services:

  asha-multipart-memory-postgres:
    container_name: asha-multipart-memory-postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./producer/src/main/resources/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql